import type { Metadata } from "next";
import { Source_Sans_3 } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar/Navbar";

const sourceSans = Source_Sans_3({
  variable: "--font-source-sans",
  subsets: ["latin", "latin-ext"], // add more subsets
  weight: ["200", "300", "400", "500", "600", "700", "800", "900"], // add desired weights
  display: "swap", // font display strategy
});

export const metadata: Metadata = {
  title: "Omar Gamal",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${sourceSans.className} antialiased`}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
